version: '3.5'
services:
    database:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: Backoffice
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: MainPassword
            volumes:
                mysql_data:/var/lib/mysql
volumes:
    mysql_data:
