version: '3.5'
services:
    database:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: Backoffice
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: MainPassword
            volumes:
                mysql_data:/var/lib/mysql
    app:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - database
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1
volumes:
    mysql_data:
